#65.Python program to demonstrate exception handling-2
try:
    l=[1,2,3,4,5]
    print(l[5])
except:
    print("an exception is raised")
else:
    print("No exception occured")
    

    
    
